---
title: "Module - Batch Correction"
author: "BTC Pipeline"
date: "`r Sys.time()`"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    code_folding: show
    theme: united
    df_print: paged
    self_contained: TRUE
params:
  project_name: 'Test'
  project_object: './data/Test_nonMalignant_reduction_object.RDS'
  input_target_variables: 'batch'
  input_integration_method: 'all'
  input_batch_step: "main"
  n_threads: 8
  n_memory: 16
  workdir: !r here::here()
  timestamp: !r Sys.Date()
  auto_save: TRUE
---

------------------------------------------------------------------------

# Project Name: `r params$project_name`

```{r setup, include = FALSE, message = FALSE, warning = FALSE, echo = FALSE}

# Project parameters 
project_name <- params$project_name
project_object <- params$project_object

# Filter and thresholds
input_integration_method <- params$input_integration_method
input_target_variables <- strsplit(
  params$input_target_variables, split = ';')[[1]]
input_batch_step <- params$input_batch_step

# Optional parameters

# Dataflow/Computational parameters
n_threads <- params$n_threads
n_memory <- params$n_memory

# Output parameters
work_directory <- params$workdir
timestamp <- params$timestamp
auto_save <- params$auto_save

# Rmarkdown options
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.height = 8, 
  fig.width = 12,
  fig.align = 'center'
  )

knitr::opts_knit$set(
  root.dir = work_directory
  )

```

## Loading library

```{r library}

library(readr)
library(dplyr)
library(ggplot2)
library(Seurat)
library(SeuratWrappers)
library(harmony)
library(batchelor)
library(kBET)

```

## Folder structure

```{r project_directory}

if(!dir.exists(work_directory)) {
  dir.create(work_directory, recursive = T)
}

for(sub_directory in c('data', 'figures', 'figures/integration')) {
  dir.create(paste0(work_directory, '/', sub_directory))
}

# Cirro-related edition
file.create('figures/integration/.empty')

```

```{r loading_rds}

# Reading seurat object
seurat_object <- readRDS(file = project_object)

# Setting random seed
random_seed <- 2203
set.seed(random_seed)

# Expanding memory
options(future.globals.maxSize = n_memory*1024^3)

```

## Input validation

```{r basic_input_validation}

# Batch method
boolean_vector <- 
  switch(input_integration_method,
  'all' = c(T, T, T, T), 
  'cca' = c(T, F, F, F),
  'rpca' = c(F, T, F, F),
  'harmony' = c(F, F, T, F),
  'mnn' = c(F, F, F, T)
)

```

## Running batch correction methods

```{r cca_integration, eval = boolean_vector[[1]]}

seurat_object <- IntegrateLayers(
  object = seurat_object, 
  method = CCAIntegration,
  orig.reduction = "pca", 
  new.reduction = "integrated.cca",
  group.by = input_target_variables,
  verbose = FALSE
)

```

```{r rpca_integration, eval = boolean_vector[[2]]}

seurat_object <- IntegrateLayers(
  object = seurat_object, 
  method = RPCAIntegration,
  orig.reduction = "pca", 
  new.reduction = "integrated.rpca",
  group.by = input_target_variables,
  verbose = FALSE
)

```

```{r harmony_integration, eval = boolean_vector[[3]]}

seurat_object <- IntegrateLayers(
  object = seurat_object, 
  method = HarmonyIntegration,
  orig.reduction = "pca", 
  new.reduction = "harmony",
  group.by = input_target_variables,
  verbose = FALSE
)

```

```{r fastmnn_integration, eval = boolean_vector[[4]]}

seurat_object <- IntegrateLayers(
  object = seurat_object, 
  method = FastMNNIntegration,
  new.reduction = "integrated.mnn",
  group.by = input_target_variables,
  verbose = FALSE
)

```

## Saving Seurat object

```{r object_dump}

if(auto_save) {
  
  saveRDS(seurat_object, file = paste0('./data/', project_name, '_', input_batch_step, '_batch_object.RDS'))
  
}

```

------------------------------------------------------------------------

## Parameters log

```{r params_log, message = FALSE, warning = FALSE, echo = FALSE}

print(params)

```

## Session info

```{r session_info, message = FALSE, warning = FALSE, echo = FALSE}

sessionInfo()

```
